#!/bin/sh
# Version X.Y.N: X.Y from the latest vX.Y.0 tag, N the number of commits made
# since it (this commit included). Enable with: ln -s ../../tools/pre-commit .git/hooks/pre-commit
tag=$(git describe --tags --abbrev=0 --match 'v[0-9]*.[0-9]*.0' 2>/dev/null) || exit 0
base=${tag#v}
base=${base%.0}
n=$(( $(git rev-list --count "$tag"..HEAD) + 1 ))
sed -i "0,/version: '[0-9.]*')/s//version: '$base.$n')/" meson.build
git add meson.build
